### ISSUE TITLE
部分文件无法下载

### ISSUE THREAD

**Issue by iceprosurface** [mamoe/mirai-console-wrapper#5]
国内源无法下载

主要是这个文件，一直都是 524
https://pan.jasonczc.cn/?/mirai/mirai-core-qqandroid/mirai-core-qqandroid-1.0.2.mp4

```
Local Core Version: 0.0.0 | Newest STABLE Core Version: 1.0.2
Updating shadowed-core from V0.0.0 -> V1.0.2
Mirai Downloader
[Mirai国内镜像] 感谢崔Cloud慷慨提供免费的国内储存分发
Progress: #########################################################  | Failed##
#####################  | FailedFailed to download resources from https://pan.jasonczc.cn/?/mirai/mirai-core-qqandroid/mirai-core-qqandroid-1.0.2.mp4 reason Server returned HTTP response code: 524 for URL: https://pan.jasonczc.cn/?/mirai/mirai-core-qqandroid/mirai-core-qqandroid-1.0.2.mp4

Failed to download resources from https://pan.jasonczc.cn/?/mirai/mirai-console/mirai-console-0.5.2.mp4 reason Server returned HTTP response code: 524 for URL: https://pan.jasonczc.cn/?/mirai/mirai-console/mirai-console-0.5.2.mp4
java.io.IOException: Server returned HTTP response code: 524 for URL: https://pan.jasonczc.cn/?/mirai/mirai-core-qqandroid/mirai-core-qqandroid-1.0.2.mp4
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1900)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268)
	at net.mamoe.mirai.console.wrapper.MiraiDownloaderImpl$downloadTask$2.invokeSuspend(MiraiDownloader.kt:87)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Failed to download resources from https://pan.jasonczc.cn/?/mirai/mirai-core-qqandroid/mirai-core-qqandroid-1.0.2.mp4 reason Server returned HTTP response code: 524 for URL: https://pan.jasonczc.cn/?/mirai/mirai-core-qqandroid/mirai-core-qqandroid-1.0.2.mp4
Please Seek For Help
java.io.IOException: Server returned HTTP response code: 524 for URL: https://pan.jasonczc.cn/?/mirai/mirai-console/mirai-console-0.5.2.mp4
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1900)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
```

> 我找个海外服试试能不能吧包搞下来

**Comment by kirainmoe** [comment]
同样的问题，手动从 mamoe/mirai-repo 下载 mirai-core-qqandroid-1.0.2.jar 放到 content 目录下后也会被 wrapper 自动删除并更新，有什么解决方案吗？

**Comment by iceprosurface** [comment]
> 我刚好也遇到了这个问题，并且我是海外服务器，应该是镜像挂了

海外国内都试过确定不能使用= =， 等下翻一下 kotlin 瞅瞅有没有办法绕过更新吧

**Comment by KunoiSayami** [comment]
Same here.

**Comment by iceprosurface** [comment]
是在不行的话可以先这么改：

mirai-console-wrapper/src/main/kotlin/net/mamoe/mirai/console/wrapper/ConsoleUpdater.kt
85 行 修改为
```kotlin
            MiraiDownloader.addTask(
                "https://raw.githubusercontent.com/mamoe/mirai-repo/master/shadow/${getProjectName()
                }/${getProjectName()}-0.5.1.jar",getContent("${getProjectName()}-0.5.2.jar")
            )
```

mirai-console-wrapper/src/main/kotlin/net/mamoe/mirai/console/wrapper/CoreUpdater.kt
41行
```kotlin
  MiraiDownloader
//                    .addTask(
//                            "https://pan.jasonczc.cn/?/mirai/mirai-core-qqandroid/mirai-core-qqandroid-$newest.mp4",
//                            getContent("mirai-core-qqandroid-jvm-$newest.jar")
//                    )
            .addTask("https://raw.githubusercontent.com/mamoe/mirai-repo/master/shadow/mirai-core-qqandroid/mirai-core-qqandroid-$newest.jar", getContent("mirai-core-qqandroid-jvm-$newest.jar"))
```

然后 maven shadowJar 自己编译一下（临时可以用一下，后面等作者更新吧）

我觉得可以从 env 里面读 cdn 配置，这样可以改镜像位置

**Comment by iceprosurface** [comment]
shadow 仓库还没有 0.5.2 的编译包，先用 0.5.1 的代替一下，也就临时策略了

**Comment by iceprosurface** [comment]
0.5.1 好像有 bug ，应该不是 wrapper 的问题

```
 14:30:21 [INFO] [NETWORK ERROR] java.lang.NoClassDefFoundError: net/mamoe/mirai/network/BotNetworkHandler
	at net.mamoe.mirai.console.command.DefaultCommands$login$$inlined$Bot$lambda$2.invoke(DefaultCommands.kt:34)
	at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.getLogger(QQAndroidBotNetworkHandler.kt:53)
	at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.closeEverythingAndRelogin(QQAndroidBotNetworkHandler.kt:147)
	at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$closeEverythingAndRelogin$1.invokeSuspend(QQAndroidBotNetworkHandler.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

那看起来只能在跑 console 那边自己编译一遍 console 解决咯

**Comment by Him188** [comment]
可临时使用这个文件, 解压后放到 `content` 目录中

[content.zip](https://github.com/mamoe/mirai-console-wrapper/files/4721611/content.zip)

**Comment by SkyMXF** [comment]
在mirai console内执行install CQHTTPMirai安装CQHTTPMirai插件的时候也有类似的问题。

直接从https://github.com/mamoe/mirai-plugins/tree/master/CQHTTPMirai下载了jar放入plugins文件夹之后，然后在console内执行reload可以解决

**Comment by Him188** [comment]
install 指令也是通过 崔云 (国内代理) 下载. 并且插件只有这唯一一个服务器.
